Catch solver error
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/ben/miniconda3/envs/research/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 1237, in run_experiment_unpack
    return run_experiment(*args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 1217, in run_experiment
    corruption = find_corruption(
                 ^^^^^^^^^^^^^^^^
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 1147, in find_corruption
    for k, (estm_res, optimizer_res, metadata) in zip(ks, res_iter):
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 880, in estimate_state_unpack
    return estimate_state(*args)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 871, in estimate_state
    optimizer_res: MyOptimizerRes = optimizer.optimize_l0_v4(setup['Phi'], setup['Y'], eps=eps, solver_args={'solver': cp.CLARABEL})
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 578, in optimize_l0_v4
    for s in soln_generator:
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 621, in optimize_l0_case
    prob.solve(**solver_args)
  File "/home/ben/miniconda3/envs/research/lib/python3.11/site-packages/cvxpy/problems/problem.py", line 503, in solve
    return solve_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/miniconda3/envs/research/lib/python3.11/site-packages/cvxpy/problems/problem.py", line 1086, in _solve
    self.unpack_results(solution, solving_chain, inverse_data)
  File "/home/ben/miniconda3/envs/research/lib/python3.11/site-packages/cvxpy/problems/problem.py", line 1411, in unpack_results
    raise error.SolverError(
cvxpy.error.SolverError: Solver 'CLARABEL' failed. Try another solver, or solve with verbose=True for more information.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/main.py", line 322, in <module>
    run_experiments(
  File "/home/ben/Projects/research-sensor-attack/bsim_v2/utils.py", line 1293, in run_experiments
    for corruption, fault_spec in tqdm(res_iter, total=len(fault_specs), smoothing=0):
  File "/home/ben/miniconda3/envs/research/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/ben/miniconda3/envs/research/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
cvxpy.error.SolverError: Solver 'CLARABEL' failed. Try another solver, or solve with verbose=True for more information.
```